version: "3.3"

services:

    php:
        image: yannoff/php-fpm:8.0-rc-fpm-alpine
        volumes:
            - ./:/var/www/html
        user: ${DOCKER_PHP_USER:-1000}:${DOCKER_PHP_GROUP:-1000}
        ports:
            - ${DOCKER_HTTP_PORT:-8000}:8888
        command:
            - php
            - -S
            - 0.0.0.0:8888
            - -t
            - public

#    mysql:
#        image: library/mysql:5.7
#        ports:
#            - ${DOCKER_MYSQL_PORT}:3306
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_USER: ${DOCKER_MYSQL_USER:-symfo5}
#            MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD:-symfo5}
#            MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE:-sf51}
#            MYSQL_ALLOW_EMPTY_PASSWORD: 1
#            TZ: Europe/Paris
#        command:
#            - mysqld
#            - "--character-set-server=utf8mb4"
#            - "--skip-character-set-client-handshake"
#            - "--collation-server=utf8mb4_unicode_ci"
#            - "--sql-mode="
#        volumes:
#            - ./:/src
#            - ./data/init:/docker-entrypoint-initdb.d/
#            - mysql-data:/var/lib/mysql
#        working_dir: /src
#        networks:
#            default:
#                aliases:
#                    - service.mysql
#
#    adminer:
#        image: adminer:standalone
#        ports:
#            - ${DOCKER_ADMINER_PORT}:8080
#        environment:
#            ADMINER_DEFAULT_SERVER: mysql
#            ADMINER_DESIGN: rmsoft_blue
#        depends_on:
#            - mysql

volumes:
    mysql-data:
